K6lOCOWHhMgw372p:
  id: K6lOCOWHhMgw372p
  title: What is Pallium CMS
  subtitle: /index
  filepath: index.md
  created: 2015-10-18T18:29:53.290Z
  modified: 2015-10-19T14:58:57.632Z
  locked: false
  domain: docs
  type: page
ffi2HXftYQFn3lzI:
  id: ffi2HXftYQFn3lzI
  title: Getting Started
  subtitle: /getting-started/index
  filepath: getting-started/index.md
  created: 2015-10-18T18:35:10.850Z
  modified: 2015-10-18T18:37:35.186Z
  locked: false
  domain: docs
  type: page
21LBBQVt8jpYKxJ4:
  id: 21LBBQVt8jpYKxJ4
  title: Configuration
  subtitle: /configuration/index
  filepath: configuration/index.md
  created: 2015-10-18T20:23:15.535Z
  modified: 2015-10-18T20:35:16.747Z
  locked: false
  domain: docs
  type: page
MNrRptIWWsNxNxMi:
  id: MNrRptIWWsNxNxMi
  title: 'Configuration: Site'
  subtitle: /configuration/site/index
  filepath: configuration/site/index.md
  created: 2015-10-18T20:33:31.949Z
  modified: 2015-10-19T14:47:41.319Z
  locked: false
  domain: docs
  type: page
nn68KnX41sUYhjAF:
  id: nn68KnX41sUYhjAF
  title: 'Configuration: Entries'
  subtitle: /configuration/entry/index
  filepath: configuration/entry/index.md
  created: 2015-10-18T20:34:34.718Z
  modified: 2015-10-19T14:47:33.442Z
  locked: false
  domain: docs
  type: page
NUYe2Uf6A4Jh7R8l:
  id: NUYe2Uf6A4Jh7R8l
  title: 'Configuration: Fields'
  subtitle: /configuration/fields/index
  filepath: configuration/fields/index.md
  created: 2015-10-19T14:48:44.925Z
  modified: 2015-10-19T14:48:44.925Z
  domain: docs
  type: page
  locked: false
kgQ0N4xiWIFi1ohl:
  id: kgQ0N4xiWIFi1ohl
  title: Plugins
  subtitle: /plugins/index
  filepath: plugins/index.md
  created: 2015-10-19T14:50:35.365Z
  modified: 2015-10-19T16:21:54.968Z
  locked: false
  domain: docs
  type: page
